services:
  marketplace_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mohajer_meal_marketplace_bot
    restart: unless-stopped
    network_mode: "host"

    ports:
      - "443:80"

    volumes:
      # Mount a named volume to /data inside the container
      - ./mohajer-db-data:/data

    env_file:
      - .env