services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mohajer_meal_marketplace_bot
    restart: unless-stopped
    network_mode: "host"

    volumes:
      # Mount a named volume to /data inside the container.
      # This will persist your SQLite database (self_market.db)
      # and the bot_persistence file across container restarts.
      - app_data:/data

    env_file:
      - .env

volumes:
  # Define the named volume that will be used for persistent storage.
  app_data:
    # driver: local # This is the default driver, can be omitted.