"""remove_simple_unique_on_listing_code_add_partial_unique_index

Revision ID: b6fabb9cda64
Revises: e0d12a68429b
Create Date: 2025-05-17 03:00:55.455753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6fabb9cda64'
down_revision: Union[str, None] = 'e0d12a68429b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index('ix_listings_university_reservation_code')
        batch_op.create_index(batch_op.f('ix_listings_university_reservation_code'), ['university_reservation_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_university_reservation_code'))
        batch_op.create_index('ix_listings_university_reservation_code', ['university_reservation_code'], unique=1)

    # ### end Alembic commands ###
